repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: ^tests/resources/
      - id: end-of-file-fixer
        exclude: ^tests/resources/
      - id: check-yaml
        args: ["--unsafe"]
      - id: check-added-large-files
      - id: check-ast
      - id: check-json
      - id: debug-statements
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: detect-private-key
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ['--maxkb=3000']


  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.6
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format


  - repo: local
    hooks:
      - id: ty
        name: Static type checking
        entry: ty check
        files: ^rmsd/.*\.py$
        language: system


  - repo: local
    hooks:

      - id: jupyisort
        name: Sorts ipynb imports
        entry: jupytext --pipe-fmt ".py" --pipe "ruff check --select I --fix -" --sync
        files: \.ipynb$
        language: python

      - id: jupyformat
        name: Fixes ipynb format
        entry: jupytext --pipe-fmt ".py" --pipe "ruff format -" --sync
        files: \.ipynb$
        language: python

      - id: nbconvert
        name: Removes ipynb content
        entry: jupyter nbconvert
        args:
          [
            "--ClearOutputPreprocessor.enabled=True",
            "--ClearMetadataPreprocessor.enabled=True",
            "--RegexRemovePreprocessor.enabled=True",
            "--to=notebook",
            "--log-level=ERROR",
            "--inplace",
          ]
        files: \.ipynb$
        language: python
